import unittest

from max_palindromes import Solution, isPalindrome

big_string = "fojnrcnerybjjghhaykxykixkojokxikyxkyahhgjjbyrencrnjofzyzeftizdmiynofcwlwcfonyimdzitfezyzqywfmxqcqhwbsmtbfberkuiukrebfbtmsbwhqcqxmfwywhoppuqnxqesiqedlpujohqpnvzvljyjlvzvnpqhojupldeqiseqxnquppohwrniimkadiwfkesjhhjsekfwidakmiingbsasadxeqxacdhxqkupyprzrcjaqtqajcrzrpypukqxhdcaxqexdasawuumyhklbhodwcmydtkfezcuesnjjnseuczefktdymcwdohblkhymuuwsdquovgnrckcpubplmueyaernzdmcmdznreayeumlpbupckcrngvouqdpsktcrqynclzrgjtplokkfihhymmgsgmmyhhifkkolptjgrzlcnyqrctksvnchfxupvsyljxzadjhohjdazxjlysvpuxfhcnwatcqotbwunztyzryjmmjyrzytznuwbtoqctawdykmoeebpeqmgbdexfwxcelvwxyrryxwvlecxwfxedbgmqepbeeblxevnmdcnrwfsaqqasfwrncdmnvexlbwaurakgpqtjpymaibpebeqlelqebepbiamypjtqpgkaruawceerqumnqbdwnbtlcootttibpdjpckqfcrmajjamrcfqkcpjdpbitttoocltbnwdbqnmuqreeyvfwueuewqyxyiaquqaiyxyqweueuwfvksskyuswbeqpihumbedwoxhufidbdifuhxowdebmuhipqebwsuykssktegrvozxyiofngmqbkiqfagxsfyllzgumemugzllyfsxgafqikbqmgnfoiyxzosthtycrjroeipdirvtrlzukccpqpcckuzlrtvridpieorjrcythtsdalhtjojbryxaoxppdxpwwbbklywnamrxtjpwtqfxyegmywwvwwymgeyxfqtwpjtxrmanwylkbbwwpxdppxoabymjvqlwqnmfzerregerrezfmnqwlqvjmybgogqdfigragpafjcyfzkqxzladjqufrrfuqjdalzxqkzfycjfapgargifdqgogarlptpazebeudrmymnvimxkssysytgujznjancjrjcnajnzjugtysysskxmivnmymrduebezaptphpmeblrzbxzzvxpwwxhiykxmbdcrwvcketekcvwrcdbmxkyihxwwpxvzzxbzrlbemhvcaswtkxbsdpalkxkddqokerskptsustbcbtsustpksrekoqddkxklapdsbxktwsacvhmjigkwrygxusxbbguwzngqoqbknehaopuvvupoahenkbqoqgnzwugbbxsuxgyrwkgikjureyadreoxreinabllbanierxoerdayerujkmjuxcoydsukgdctdcnrsqxcrzvmxmvzrcxqsrncdtcdgkusdyocxuuznoynsubjvoibuxfddwfogofwddfxubiovjbusnyonzuuubdw"


big_string_2 = "xdnrbnlkrrnwmovtudurxwkxwugzpimicxoncgwngnwgcnoxcimipzguwxkwxrudutvomwnrrklnbrndhijluyxlwrilgzuxysovxzsbixiauiikfwjjdmxozdepyazedzxodwwdoxzdezaypedzoxmdjjwfkiiuaixibszxvosyxuzglirwlxyekhjfwrpafcszsxkhtswrhhhqbfqyuxeztwrumkqhhcutyytuchhqkmurwtzexuyqfbqhhhrwsthkxszscfaprwiwvvjlncnjjprkvvueaxojbekzcqaptrsklyeknxlgmggmglxnkeylksrtpaqczkebjoxaeuvvkrpjjncnljvvwicnivwnzxbyvqjkusbvqzujfdpmkmjzhxxhxvhfriqvicerrecivqirfhvxhxxhzjmkmpdfjuzqvbsukjqvybxznwvqrmfactlrjkgairdnioxwokxclyxtrrteqatzreikexuuaqqauuxekierztaqetrrtxylcxkowxoindriagkjrltcafmregexnxhbthhkhmgvmhwsgzcfytkrracqbjykqdqxhmlkhoybbyohklmhxqdqkyjbqcarrktyfczgswhmvgmhkhhtbhxnxegcootmgfkvldlftjvqzburabzskurkqtqtjiwwvkwezzewkvwwijtqtqkrukszbarubzqvjtfldlvkfgmtosjymrphkafbuvyzhiwvauyowadttsvcpatqegjvtbldxxdlbtvjgeqtapcvsttdawoyuavwihzyvubfakhprmyjsaokjotxdaltebkbwfrzivgftbjroyqflfmuhkvnzcfgxpqyzzyqpxgfcznvkhumflfqyorjbtfgvizrfwbkbetladxtojkoanboctznsjgifuhakzqfdrnzmqphtgmdtcgqvlyevncovhkvpakkapvkhvocnveylvqgctdmgthpqmznrdfqzkahufigjsnztcobniedaxatzltsajpslqzezdpqhfdxmbfgqvfrovbokqwgdkmsfuufsmkdgwqkobvorfvqgfbmxdfhqpdzezqlspjastlztaxadepxyfxqmlaupuagrjggfwyxvfatzteskeyjmrrfuwwlomylylymolwwufrrmjyeksetztafvxywfggjrgaupualmqxfyxpwhkzinywcjxqdhvsmbhbzxpwstgjfmgpbsziyamjcqjfjqcjmayizsbpgmfjgtswpxzbhbmsvhdqxjcwynizcebhmghbgzbtdvoedqouqlknhfgdrdxjlczyaychfsqqzebezqqsfhcyayzcljxdrdgfhnklquoqdeovdtbzgbhgmhbexsfbmudjufklmskuksekvrhbcfklvfzjhvmhbxzxsrbimhkpnnpkhmibrsxzxbhmvhjzfvlkfcbhrvkeskuksmlkfujdumbfsxwlvfyddwapgmhnrnzrqetwstoecqflcipnolmhxxokfqgqzxmxmxzqgqfkoxxhmlonpiclfqceotswteqrznrnhmgpawddyfvlwgplbwqodjzedfksdmtfiahtqifefmpckukhuruwchspshcwuruhkukcpmfefiqthaiftmdskfdezjdoqwblpgfvqfkvhfslochdyptixpizbhhlvvilaguxcshlxhwhhbjitugutijbhhwhxlhscxugalivvlhhbzipxitpydhcolsfhvkfqvwogzrgrzrdsimejmhisuzqltzkqytaxzphdvfjcdimvkvmidcjfvdhpzxatyqkztlqzusihmjemisdrzrgrmilcvuucscyjogmyzqogkdsgwgolndluoxgxoetoduxvxudoteoxgxouldnlogwgsdkgoqzymgojycscuuvclimwlkvmygbwptzkgftlhvqtyowpsaltvhavkocmwrrirrwmcokvahvtlaspwoytqvhltfgkztpwbgymvklwjkvc"



class TestSolution(unittest.TestCase):

    def test_0(self):
        s = Solution()
        result = s.maxPalindromes(big_string_2, 78)
        self.assertEqual(22, result)

    def test_1(self):
        s = Solution()
        result = s.maxPalindromes(big_string, 24)
        self.assertEqual(29, result)

    def test_2(self):
        s = Solution()
        result = s.maxPalindromes(s = "aba", k = 3)
        self.assertEqual(1, result)

    def test_3(self):
        s = Solution()
        result = s.maxPalindromes(s = "abaccdbbd", k = 3)
        self.assertEqual(2, result)

    def test_4(self):
        self.assertEqual(False, isPalindrome('adbcda', 1, 3))

        s = Solution()
        result = s.maxPalindromes(s = "adbcda", k = 2)
        self.assertEqual(0, result)

try:
    unittest.main()
except SystemExit:
    None







